version: 2
jobs:
  build:
    machine:
      go:
        version: 1.9.2
      services:
        - docker
    working_directory: $HOME/go/src/github.com/solarwinds/docker-plugin-papertrail
    steps:
      - checkout
      - run: export GOPATH=$HOME/go
      - run: ./build.sh